### ISSUE TITLE
✨ Mobile | GitHub on profiles

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#1005]
Cc: @tkapa @matt-goldman-ssw @adamcogan @sethdaily 

Hi team

### Pain

In #799 we added the ability to add LinkedIn profiles to user profiles in the app, as a stopgap until a more proper IdentityServer integration could be completed. Currently we have an icon for GitHub but is currently disabled.

### Suggested Solution

We should hook up the GitHub button similarly to the LinkedIn button for the time being.

### Tasks

- [ ] Add the ability to save a GitHub profile against a user
- [ ] Ensure other users can tap this button to visit the link

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by zacharykeeping** [comment]
Done - GitHub can now be set on profiles.

<img src="https://github.com/user-attachments/assets/1fa60032-fb6d-4846-b12a-43a6312032b3" width="400" />

**Figure: User profile with GitHub set**
