### ISSUE TITLE
🐛 NDC - Login process causing friction

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Rewards.Mobile#1008]
Cc: @adamcogan @joshbermanssw @wicksipedia 

Hi Tylah

### Describe the Bug

The login process is confusing with the IdentityServer popups
* Related video: [IdentityServer login issue](https://sswcom-my.sharepoint.com/personal/mattgoldman_ssw_com_au/_layouts/15/stream.aspx?id=%2Fpersonal%2Fmattgoldman%5Fssw%5Fcom%5Fau%2FDocuments%2FRecordings%2FCall%20with%20Adam%20and%205%20others%2D20240828%5F231818%2DMeeting%20Recording%2Emp4&ct=1726567394067&or=Outlook%2DBody&cid=ED50496A%2DD89B%2D4E47%2DA28B%2D770041439447&ga=1&LOF=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E9567b4ca%2D1623%2D40e7%2Da125%2D9a1beaf3d20e)

Current process:
1. Create an account
2. Enter details
3. popup comes up
4. email verification
5. return to the app (popup hasn't gone away)
6. close the popup
7. click 'sign in'
8. another popup to sign in

### To Reproduce

1. Open the app
2. Create account

### Expected Behavior

I would like to stay on the SSW Rewards page - no popups

I would expect:
1. Create account
2. Enter details
3. Email verification (returns the user to the app)
4. I'm already logged in

### Tasks

- [x] Investigate good examples of Sign-up process
- [x] ⚠️App - Authentication - open in in-app?
- [x] Email verification - open in default browser
- [x] Email verification - automatically redirect to the app on confirmation (Has to be done in SSW Identity Server)
- [x] When the User is returned to the app - browser pop-up should be gone.
- [x] New Password - Simplify requirements. 
Change from 
Min Password Length - **16** characters. At least 1 Capital letter **AND** 1 Special character
to
Min Password Length - **12** characters. At least 1 Capital letter **OR** 1 Special character
- [x] After Password requirements are changed, send As per our conversation email to track the history of this decision.
- [x] User should be automatically signed in after confirmation

**Note: Current Password rules - 16 characters, 1 Capital letter, 1 Special characters, no sequential characters**

### Screenshots

![Image](https://github.com/user-attachments/assets/435838bf-930a-4106-9f35-444b7f574e2e)

Thanks!

**Comment by sethdaily** [comment]
@zacharykeeping 
You moved this to blocked but no comments...what is the blocker?

**Comment by vladislav-kir** [comment]
In-app browser in android is called "Custom Tabs" - https://developer.chrome.com/docs/android/custom-tabs/

As per https://learn.microsoft.com/en-us/dotnet/maui/platform-integration/communication/authentication?view=net-maui-9.0&tabs=android#platform-differences, Custom Tabs are used whenever available, otherwise the system browser is used as a fallback.

For some reason, as in case with @jerryluossw, on some devices `IWebAuthenticator` fails to use custom tabs.

**Comment by wicksipedia** [comment]
When I looked at 

https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/a8a1391e5e8476f8b158fa64b6db1024fd23cf67/src/MobileUI/Common/Api/AuthBrowser.cs#L10

It was different to the Duende sample - note the `.Default` usage

https://github.com/DuendeSoftware/Samples/blob/f04afd7ec7d1483b9e2d0a703bf898fed1c88cc0/various/clients/Maui/MauiApp1/MauiApp1/MauiAuthenticationBrowser.cs#L12

Could this affect things?

**Comment by vladislav-kir** [comment]
Mobile app version 3.0.47 contains these changes

**Comment by vladislav-kir** [comment]
As per feedback from @zacharykeeping , there is an issue with autologin in Safari on iOS:

I created a new user using a dummy email and received the email confirmation link, but tapping the link just brings up this error in Safari:
 
![Image](https://github.com/user-attachments/assets/2e30d0b9-7e74-4225-b20c-c21a192223b5)

Figure: Error in Safari when tapping the confirm email button

That being said, it still seems to confirm my email and I’m then able to log in using that account.



Reopening the issue.

**Comment by vladislav-kir** [comment]
The changes passed testing in Test Flight and are deployed
