### ISSUE TITLE
♻️ Add tabs to QR code page to show 'Mine' and 'Scan'

### ISSUE THREAD

**Issue by matt-goldman-ssw** [SSWConsulting/SSW.Rewards.Mobile#1009]
Cc: @adamcogan @wicksipedia 

Hi

### Pain

Some people find the layout and location of various controls within the app confusing. In particular, when on the QR scanning screen, it's not immediately apparent that you need to open the menu from your avatar to get to your own QR code.

### What code could be improved?

@wicksipedia has suggested we could follow the same approach LinkedIn uses. In this case there is a QR screen which lets you either share your QR code or scan someone else's/

![Image](https://github.com/user-attachments/assets/4ed1c060-f023-4396-b4dc-ae05dd0c7433)

**Figure:** In the LinkedIn app, the QR screen has tabs that allow you to scan someone else's QR code or share your own.

### Tasks

- [ ] Add tabs to the QR screen 
- [ ] Make one tab the scanner
- [ ] Make the other tab show your own QR code

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

### More Information

Consider using Sharpnado Tabs

Thanks!
