### ISSUE TITLE
✨ Show unrequited friends

### ISSUE THREAD

**Issue by matt-goldman-ssw** [SSWConsulting/SSW.Rewards.Mobile#1011]
Cc: @wicksipedia @adamcogan 

Hi

### Pain

When you scan a user they show up in your Friends list, but you do not show up in theirs. This can be confusing to some people who interpret it as making a mutual connection. When they get scanned by someone they expect to see that person as a friend but don't - only that person sees them.

### Suggested Solution

When someone has scanned you, but you have not scanned them, you should see something that indicates as such. Some suggestions:

* On the Friends tab, show people you have scanned, then (sorted at the end) show people that have scanned you but you have not scanned
* Show these people in grayscale
* Show a badge on the tab showing number of people that have scanned you that you have not scanned
* Add a tooltip to the badge

### Tasks

- [ ] Run the suggestions by a UX designer
- [ ] Get an approved design
- [ ] Implement

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!
