### ISSUE TITLE
♻️ Mobile | "My QR Code" should link to the new scanner page

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#1025]
Cc: @adamcogan @matt-goldman-ssw 

Hi team

### Pain

As per Adam's email (subject "Rewards - QR code not going to new screen") the "My QR Code" button in the flyout still opens the old QR code popup

### What code could be improved?

This button should be updated to open the new Scanner page, with the QR code as the default tab.

### Tasks

- [ ] Hook up My QR Code button to the updated Scanner page
- [ ] Ensure the QR tab is open by default when opened by the button

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

### Screenshots

![Image](https://github.com/user-attachments/assets/bbe952fa-635d-45ca-bc07-58dc20da384b)

**Figure: My QR Code should go to the scanner page**

Thanks!

**Comment by zacharykeeping** [comment]
As per my conversation with Seth, we should probably just kill the button in the flyout.
