### ISSUE TITLE
♻️ Mobile | Settings page improvements

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#1057]
Cc: @adamcogan @sethdaily 

Hi

### What code could be improved?

As per @adamcogan's email (subject: "Rewards | My Settings looks worse than the video prototype ⚠️"), the following improvements should be made to the Settings page in the app:

### Tasks

- [ ] Add heading to page "SSW Rewards  |  My Settings
- [ ] Add logo in the deadspace (box in image below)
- [ ] Change "Replay Intro" to "Getting Started 🎉"
- [ ] Fix Getting Started popup on tablets (see second image)

![Image](https://github.com/user-attachments/assets/883dd97b-d41b-4e09-a4fb-18e57ed4aa73)

**Figure: Box where SSW logo should be**

![Image](https://github.com/user-attachments/assets/1f99e810-6c17-4a09-a2fd-d3bc6ac94281)

**Figure: Getting Started popup doesn't render correctly on a tablet**

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!
