### ISSUE TITLE
🐛[urgent] Common should not reference domain

### ISSUE THREAD

**Issue by matt-goldman-ssw** [SSWConsulting/SSW.Rewards.Mobile#1093]
Cc: @zacharykeeping 

Hi Zach

### Describe the Bug

https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/ce2d6f6ff79a091b78b5643dc3ee7fd6c8bc583d/src/Common/Shared.csproj#L16

The `Common` project has a dependency on `Domain` - and this means the UI does too. This should not be there and breaks CA principles.

### To Reproduce

1.N/A

### Expected Behavior

UI should not have a dependency on domain

### Tasks

- [ ] Investigate who added this (if it was me feel free to publicly shame me)
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] Dependency on `Domain` in `Common` removed
- [ ] Any requisite refactoring completed

### Environment

- Device: [e.g. iPhone 12]

### Screenshots

Thanks!

**Comment by zacharykeeping** [comment]
Looks like the change is from here: https://github.com/SSWConsulting/SSW.Rewards.Mobile/pull/937
