### ISSUE TITLE
♻️ 🔒 Don't allow non-secure URLs

### ISSUE THREAD

**Issue by matt-goldman-ssw** [SSWConsulting/SSW.Rewards.Mobile#1100]
Cc:

Hi @zacharykeeping 

### Pain

During the Sprint Review you should me a PR (which I approved #1078) which allows people to save either an `http://` url or `https://`/

We **should not** allow `http` URLs in the app - don't forget we are making these available for people to open from others' profiles. 

### What code could be improved?

Check the URL before saving for `http://`, and if we find it, replace it with `https://`. This can be done in the API without redeploying the app and doesn't break the current validation.

#### FAQ
* **What if someone's site doesn't support `https` and it breaks the link?**
    * Good.

### Tasks

- [x] Update the command that saves the URLs
- [x] Ensure the UI is updated with the corrected URL on callback

### Acceptance Criteria

- [x] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [x] Non-secure URLs cannot be saved in the app

### Screenshots

Thanks!
