### ISSUE TITLE
✨ Recent activity - merge 'scanned' and 'attended' achievements

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Rewards.Mobile#1107]
Cc:

Hi Zach

### Pain

There is no difference between 'scanned' and 'attended' achievements - but they clutter up the user profile UI in the app

### Suggested Solution

Merge those two types of achievements so I only see 1 feed of activity on a user's profile

### Tasks

- [ ] profile UI - investigate merging the 'last seen' and 'recent activity' - see image 1
- [ ] profile UI - there should be only 1 section called 'recent activity'
- [ ] achievements - I think this would mean merging 'scanned' and 'attended'
- [ ] get it checked by Goldie then myself

### Screenshots

![Image](https://github.com/user-attachments/assets/23918e93-88ef-40fc-9e57-711dd0d33723)
Figure: Image 1 - Having both of these on here is overcomplicated - it should just be 'recent activity'

![Image](https://github.com/user-attachments/assets/4fbebadf-2239-4a0d-8221-9eb0a4ddc836)
Figure: Image 2 - I think it would require merging 'scanned' and 'attended'

Thanks!

**Comment by matt-goldman-ssw** [comment]
Hi @sethdaily 

For my 2c worth, while this is not a technically difficult task, I think it needs some consideration in the broader context of the plans for the app. Keeping them separate gives us flexibility that we lose if we merge them. There's nothing stopping us displaying them all the same way in the UI irrespective of the type defined in the back end, so I would suggest at most just updating how we display them.

But I think we need to understand better how we want this to work and what we want the user experience to be. And whether we have bigger plans around location-based functionality.

Do you want to chat about this more in person when you're back from OS?
