### ISSUE TITLE
✨ Admin portal - sort by date range

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Rewards.Mobile#1115]
Cc: @landonmaxwell

Hi Zach

### Pain

Prize draw page - Current views only allow: Forever, Today, ThisWeek, ThisYear, ThisMonth

### Suggested Solution

Prize draw page - add sort by date range. 
Note - should also fix the current setup to have spaces

### Tasks

- [ ] Add sort by date range
- [ ] Add spaces to the filters e.g. ThisWeek should be This week

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] ...

### Screenshots

Thanks!
