### ISSUE TITLE
🐛 NDC Porto - lots of crashes (from lots of usage!)

### ISSUE THREAD

**Issue by sethdaily** [SSWConsulting/SSW.Rewards.Mobile#1119]
Cc: @jeanthirion @adamcogan @isaaclombardssw @freego1783

### Hi Zach (or whoever picks this up)
This is an important one ⚠️

### Describe the Bug

On October 18 (the last day of NDC Porto), we had a lot of people using the app 😁 and we noticed the app going unresponsive (lots of timeouts) and not being able to log in. See logs below. Something must be causing those timeouts.

### See the logs:

1. Go to [Azure | SSW Rewards Prod | Monitoring | Logs](https://portal.azure.com/#@sswcom.onmicrosoft.com/resource/subscriptions/b8b18dcf-d83b-47e2-9886-00c2e983629e/resourceGroups/SSW.Rewards.Prod/providers/Microsoft.Insights/components/ai-sswrewards-prod/logs)
2. Time range - set to Oct 13-19 (NDC Porto)
3. Check exceptions - see image below (spikes around 2:50pmUTC)

### Tasks

- [x] Investigate
- [x] Fix
- [ ] Check retention policy
- [ ] Make sure we keep a year's worth of data, put in cold storage if needed (so we don't struggle to find data like this in the future)

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [x] Find out what was going unresponsive and why - write this in this PBI comments
- [x] Make sure the app doesn't go unresponsive with a lot of usage

### Environment

- Device: all devices
- OS: all
- SSW Rewards version 3.0.40

### Screenshots

![Image](https://github.com/user-attachments/assets/abc099de-cec8-4bd8-a1fe-db72264eba76)
**Figure: find the logs like this**

Thanks!

**Comment by jernejk** [comment]
Initial investigation so far for the period of 16/10 - 19/10/2024.

## 1. Azure SQL Server

Azure SQL Server is on B tier with 5 DTUs, 2 GB ram and 1/2 CPU cores (shared core across other B-tier SQL Servers).

It appears that SQL Server can get overwhelmed pretty quickly and can take some time before it can recover.

![Image](https://github.com/user-attachments/assets/258cce15-8e82-432a-abc5-41a8291fbe61)

**Figure: SQL Server max-out DTUs (5 DTU) several times which would cause timeouts.**

![Image](https://github.com/user-attachments/assets/054b5af6-7822-4076-abf6-505c1f3626fb)

**Figure: While we can't get SQL query performance diagnostics for that period, we can see that some days we have queries that take longer than a minute. This one was for achievements per user.**

**Recommendation:** Investigate which tier would be best. Just upgrading to S3 would probably be sufficient but might not cost-effective as Rewards app have major spikes only a few days per month.

## 2. Lots of requests identical requests

Most common requests are for getting a leaderboard, achievements and user information like list of employees, roles, etc.

![Image](https://github.com/user-attachments/assets/32ab9d3c-f0a7-45fd-ab66-23d30216c525)

**Figure: Looking at average execution, the timings are not great but not terrible enough to bring down the service.**

While some of these requests are slow, it's the requests that timeout that causes the issues (looking at the 99th percentiles instead of avg).

![Image](https://github.com/user-attachments/assets/96f4a97f-4fde-41ad-8016-0524da155b14)

**Figure: Looking at 99th percentile, we can see several requests taking ~1 min which might be due to timeouts!**

**Recommendations:**
1. Improve EF Core queries where we can (majority issues align with SQL Server higher loads)
2. Cache values that maybe not change quickly. Just 1 min cache with smart reset logic can significantly improve performance of endpoints like leaderboard.
3. Investigate indexes for tables (many do not have any additional indexes)


I'll continue investigating as I'm getting more access to data and permissions to run necessary diagnostics.

**Comment by jernejk** [comment]
The most expensive SQL query appears to be fetching data for a user.

Endpoint: /api/user/{id}

There are a couple of queries and the one that takes most time is used predominantly to determine user's rank.

![Image](https://github.com/user-attachments/assets/24e5c30c-37e5-44f7-a386-ff6df16dba1f)

**Figure: Query plan for the query. It appears to consume ~210MB RAM to complete.**

It also returned 10k rows that is roughly 2MB for Web API to download and parse from SQL Server.

To improve performance, rank will be calculated separately and later cached, as we can fetch user profile data separately for just 1 user.

![Image](https://github.com/user-attachments/assets/75abe646-74bc-4e72-96af-e61e164aedd8)

**Figure: Query plan that will be used for determining user's rank and can be cached. It appears to only needs 64kB.**

This should significantly reduce stress on SQL Server on mobile app startup and looking at profiles.

**Comment by jernejk** [comment]
I managed to find the reason why Web API snowballs out of control as soon some requests reached >500 ms.

In `PerformanceBehaviour.cs` we log issues with performance. The irony is that fetching the data for creating the log is very heavy query. Based on my calculations, Azure SQL with current 2GB RAM can run less  than 20 `_userService.GetUser` but this would force to run on almost on any expensive query once load on Azure SQL reaches a particular load.

```cs
if (userId > 0)
{
    var user = await _userService.GetUser(userId, cancellationToken);

    userName = user.FullName;
}
```

This generates an entire leaderboard and fully populates single profile only to dispose everything but `FullName`.

**Comment by jernejk** [comment]
A simple load test with Bombardier (as per SSW Rules for performance tests), I have tested one of the endpoints that took a very long to process at NDC Porto.

## Before upgrading Azure SQL from B to S0

```ps1
bombardier -c 10 -d 60s -m GET `
-H "Authorization: Bearer {{token}}" `
https://api.rewards.ssw.com.au/api/user/GetUser/9
```

Single run: ~2 seconds

### 10 concurrent users
Load test: 0 success, 0 req/sec, 29 timeouts
Single run 1 min after load test: ~10 seconds

![Image](https://github.com/user-attachments/assets/8c42f403-5b95-4be2-a45e-f9ad88be1204)
**Figure: In 1 minute load test with 10 concurrent users we had 0 successful responses and 29 timeouts!**

![Image](https://github.com/user-attachments/assets/bf457f51-8e95-4573-a71e-200ab7cb464c)
**Figure: Even a few minutes later, it takes 5x time longer to run.**

### 1 concurrent user
Load test: 1 success, 0 req/sec, 6 timeouts
Single run after above test: ~3.6 seconds

![Image](https://github.com/user-attachments/assets/0e830a5b-624c-4239-bb54-eba8db4b5164)
**Figure: In 1 minute load test with 1 concurrent users we had 1 successful response and 6 timeouts!**

![Image](https://github.com/user-attachments/assets/a6e065ec-8d88-4d49-bf89-296cac8369d3)
**Figure: Even a few minutes later, it takes 2x time longer to run.**

**NOTE: This is the gentles performance test we can do with Bombardier.**

**Comment by jernejk** [comment]
## Summary of above statistic from Azure SQL B to S0

| Endpoint Scenario | single run (B) | req/s (B) | successes (B) | fails (B) | single run (S0) | req/s (S0) | successes (S0) | fails (B) |
| ----------------- | -------------- | --------- | ------------- | --------- | --------------- | -----------| -------------- | --------- |
| Get User by ID (1 threat) | ~2 sec | 0.09 req/s | 1            | 6         | 1.3 sec (-35%)  | 0.72 (+800%) | 39 (+3900%)  | 0 (-100%) |
| Get User by ID (10 threats) | ~2 sec | 1.89 req/s | 0            | 110     | 1.3 sec (-35%)  | 1.69 (-11%)  | 0 (+0%)      | 101 (-8%) |
| Leadeboard (1 threat) | ~2.5 sec   | 0.09 req/s | 0            | 6         | 1.2 sec (-52%)  | 0.37 (+411%) | 30 (+inf)    | 0 (-100%) |
| Leadeboard (10 threats) | ~2.5 sec | 4.09 req/s | 0            | 215       | 1.2 sec (-52%)  | 2.73 (-49%)  | 0 (+0%)      | 152 (-41%) |


Single runs are nearly double the speed and single concurrent user has performance improvement of 3900%+ while having 0 crashes. Web API still can't handle 10 concurrent users but it does handle them more gracefully with fewer fails.

**Comment by jernejk** [comment]
PRs #1130 and #1131 are in. Here are updated results.

| Endpoint Scenario         | Upgrade Type   | Single Run         | Req/s         | Successes       | Fails         |
|---------------------------|----------------|--------------------|---------------|-----------------|---------------|
| Get User by ID (1 threat) | B              | ~2 sec             | 0.09 req/s    | 1               | 6             |
|                           | S0             | 1.3 sec (-35%)     | 0.72 (+800%)  | 39 (+3900%)     | 0 (-100%)     |
|                           | S0 + fixes     | ~800 ms (-60%)     | 0.85 (+844%)  | 48 (+4700%)     | 0 (-100%)     |
| Get User by ID (10 threats)| B             | ~2 sec             | 1.89 req/s    | 0               | 110           |
|                           | S0             | 1.3 sec (-35%)     | 1.69 (-11%)   | 0 (+0%)         | 101 (-8%)     |
|                           | S0 + fixes     | ~800 ms (-60%)     | 2.34 (+24%)   | 0 (+0%)         | 135 (+23%)    |
| Leaderboard (1 threat)    | B              | ~2.5 sec           | 0.09 req/s    | 0               | 6             |
|                           | S0             | 1.2 sec (-52%)     | 0.37 (+411%)  | 30 (3000%+)     | 0 (-100%)     |
|                           | S0 + fixes     | ~800 ms (-68%)     | 0.57 (+533%)  | 42 (4000%+)     | 0 (-100%)     |
| Leaderboard (10 threats)  | B              | ~2.5 sec           | 4.09 req/s    | 0               | 215           |
|                           | S0             | 1.2 sec (-52%)     | 2.73 (-49%)   | 0 (+0%)         | 152 (-41%)    |
|                           | S0 + fixes     | ~800 ms (-68%)     | 2.91 (-29%)   | 0 (+0%)         | 163 (-24%)    |

**Comment by jernejk** [comment]
![Image](https://github.com/user-attachments/assets/5756e6e8-628a-4c2e-8d50-344821334b41)

Suspected SQL queries now will have origin info baked into the SQL query itself for easier diagnostics.

#1141

**Comment by jernejk** [comment]
**Work in progress**

PRs #1130 and #1131 are in. Here are updated results.

| Endpoint Scenario         | Upgrade Type   | Single Run         | Req/s         | Successes       | Fails         |
|---------------------------|----------------|--------------------|---------------|-----------------|---------------|
| Get User by ID (1 threat) | B              | ~2 sec             | 0.09 req/s    | 1               | 6             |
|                           | S0 + #1 fixes       | ~800 ms (-60%)     | 0.85 (+844%)  | 48 (+4700%)     | 0 (-100%)     |
|                           | S0 + #2 fixes       | ~60 ms (-60%)     | 10.49 (+844%)  | 629 (+4700%)     | 0 (-100%)     |
| Get User by ID (10 threats)| B             | ~2 sec             | 1.89 req/s    | 0               | 110           |
|                           | S0 + #1 fixes     | ~800 ms (-60%)     | 2.34 (+24%)   | 0 (+0%)         | 135 (+23%)    |
|                           | S0 + #2 fixes     | ~60 ms (-60%)     | 4.65 (+24%)   | 288 (+0%)         | 1 (+23%)    |
| Leaderboard (1 threat)    | B              | ~2.5 sec           | 0.09 req/s    | 0               | 6             |
|                           | S0 + #1 fixes     | ~800 ms (-68%)     | 0.57 (+533%)  | 42 (4200%+)     | 0 (-100%)     |
|                           | S0 + #2 fixes     | ~300 ms (-68%)     | 0.57 (+533%)  | 42 (4200%+)     | 0 (-100%)     |
| Leaderboard (10 threats)  | B              | ~2.5 sec           | 4.09 req/s    | 0               | 215           |
|                           | S0 + #1 fixes     | ~800 ms (-68%)     | 2.91 (-29%)   | 0 (+0%)         | 163 (-24%)    |
|                           | S0 + #2 fixes     | ~300 ms (-68%)     | 2.91 (-29%)   | 0 (+0%)         | 163 (-24%)    |

**Comment by jernejk** [comment]
1st fixes - #1130 and #1131
2nd fixes - #1147 and #1149
3rd fixes - #1153 

| Endpoint Scenario         | Upgrade Type   | Single Run         | Req/s         | Successes       | Fails         |
|---------------------------|----------------|--------------------|---------------|-----------------|---------------|
| Get User by ID (1 threat) | B              | ~2 sec             | 0.09 req/s    | 1               | 6             |
|                           | S0 + 1st fixes       | ~800 ms (-60%)     | 0.85 (+844%)  | 48 (+4700%)     | 0 (-100%)     |
|                           | S0 + 2nd fixes       | ~60 ms (-97%)      | 10.49 (+11544%) | 629 (+62800%)    | 0 (-100%)     |
|                           | **S0 + 3rd fixes**       | **~60 ms (-97%)**      | **28.92 (+31933%)** | **1734 (+173300%)**  | **0 (-100%)**     |
| Get User by ID (10 threats)| B             | ~2 sec             | 1.89 req/s    | 0               | 110           |
|                           | S0 + 1st fixes     | ~800 ms (-60%)     | 2.34 (+24%)   | 0 (+0%)         | 135 (+23%)    |
|                           | S0 + 2nd fixes     | ~60 ms (-97%)      | 4.65 (+146%)  | 288 (+28800%)    | 1 (-99%)      |
|                           | **S0 + 3rd fixes**     | **~60 ms (-97%)**      | **26.78 (+1317%)**  | **1614 (+161400%)** | **0 (-100%)**     |
| Leaderboard (1 threat)    | B              | ~2.5 sec           | 0.09 req/s    | 0               | 6             |
|                           | S0 + 1st fixes     | ~800 ms (-68%)     | 0.57 (+533%)  | 42 (+4200%)      | 0 (-100%)     |
|                           | S0 + 2nd fixes     | ~300 ms (-88%)     | 1.8 (+1900%)  | 110 (+11000%)    | 0 (-100%)     |
|                           | **S0 + 3rd fixes**     | **~90 ms (-96%)**      | **19.08 (+21100%)**  | **1115 (+11500%)**     | **0 (-100%)**     |
| Leaderboard (10 threats)  | B              | ~2.5 sec           | 4.09 req/s    | 0               | 215           |
|                           | S0 + 1st fixes     | ~800 ms (-68%)     | 2.91 (-29%)   | 0 (+0%)         | 163 (-24%)    |
|                           | S0 + 2nd fixes     | ~300 ms (-88%)     | 0.86 (-79%)   | 1 (+100%)       | 61 (-72%)     |
|                           | **S0 + 3rd fixes**     | **~90 ms (-96%)**     | **46 (+1024%)**   | **2769 (+276900%)**    | **0 (-100%)**     |

**Comment by jernejk** [comment]
Major stability issues from NDC Porto are now fixed. More relevant issues will be created as separate issues.
