### ISSUE TITLE
DevOps - Clean up environments and pipelines

### ISSUE THREAD

**Issue by lukecookssw** [SSWConsulting/SSW.Rewards.Mobile#331]
@wicksipedia @william-liebenberg @matt-goldman @lukecookssw 
## EPIC

The environments and infra around the Rewards environments require work.

- [x] SSWConsulting/SSW.Rewards.Mobile#332

- [x] SSWConsulting/SSW.Rewards.API#50
- [x] SSWConsulting/SSW.Rewards.Mobile#334

### Acceptance Criteria

1. API Infra is deployed and maintained across Dev, Staging and Prod environments using GitHub Workflows
2. Rewards API is deployed to Dev, Staging and Prod environments using GitHub Workflows
3. Mobile app build number is auto-incremented
4. Mobile app is deployed to App Center using GitHub Releases

**Comment by AntPolkanov** [comment]
The last outstanding task #334 was closed recently, so closing the ticket.
Currently GitHub Actions deploy Admin, API and Mobile app.
