### ISSUE TITLE
✨ Track events for better analytics

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#489]
Cc:

Hi 
  
### Pain

We don't currently have a good understanding of how people use the app, e.g. what screens they visit, how long they spend there, etc.

### Suggested Solution

We're already using [AppCenter](https://appcenter.ms) which we can use to track events. We just need to do it.

### Tasks

- [ ] Develop list of events to track
- [ ] Develop analytics report
- [ ] Add tracking of desired events to the app

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

### Screenshots

Thanks!
