### ISSUE TITLE
♻️ Add "This week" to the leaderboard

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#491]
Cc: @adamcogan @ulyssesmaclaren @william-liebenberg @bradystroud 

Watch the idea - https://www.youtube.com/watch?v=qLeeRmg87GY&t=210s

### Pain

The leaderboard in the app shows a lot of people with a lot of points, which makes it seem uncompetitive. By filtering to "this week" by default, people will be encouraged and feel like they are in with more of a chance. Additionally, it helps scope the leaderboard to events like NDC.

### What code could be improved?

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/1d1f509b-6e57-4d8d-95ee-880319590756" width=250/>

**Figure: Before - leaderboard shows month, year, and all time**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/03086671-d76e-4255-898e-05cc51641b4e" width=250/>

**Figure: After - leaderboard shows week, month, year, and all time**

### Tasks

- [ ] Update API leaderboard filter to include "This week"
- [ ] Add "This week" tab to mobile app UI
- [ ] Make "This week" the default view

Thanks!

**Comment by JeanThirion** [comment]
(sadly can't edit my CTF answer after replying - giving my feedback here)
I don't think this makes much of a difference, and I think our efforts would be better spent elsewhere. If usage carry on as it goes now, this is going to look TERRIBLE 😅

**Comment by tkapa** [comment]
Interesting proposition, as Jean as said, though, if there isn't enough activity to support a weekly feed, maybe it isn't worth it. Though it seems relatively low effort.

**Comment by JackDevAU** [comment]
I'm also on the side of, I don't think this adds any value. If activity is low, the monthly leaderboard should be enough. I think a real driver would be through further gamification.

**Comment by tomek-i** [comment]
I agree with the rest of the people here, if there is no activity it might actually hurt more ... 
maybe instead of that you can "add friends" and see a leaderboard between your mates and how you compare to them

**Comment by ricksu978** [comment]
This might be useful when activity is high during NDC week, but it might look bad through out the year.

**Comment by JimmyChenSSW** [comment]
Good, motivate people use the app more, especially new users

**Comment by christoment** [comment]
Agree that looking at massive amount of points as the top of leaderboard is not encouraging at all 😞 
Some other gamification (like Duolingo) also resets the leaderboard every month - I like this idea since it allows everyone (including late joiners) to be in the top of the leaderboard. 😄

**Comment by KahaMason** [comment]
I think the main factor for this is the volume of activity. If there isn't enough happening on a weekly basis, the value of this diminishes. Unless we pad it with weekly repeatable tasks for people to complete to accumulate points.

**Comment by PennyWalker** [comment]
I think this is important, it's going to be really hard to get engagement from new people if other people are 25,000 points in front.

**Comment by AnkyChe** [comment]
Good idea to motivate new users!

**Comment by sylhuang** [comment]
I think it's less important than the other features that will bring users actual value. If there is no enough content/activities to keep users enaged with the app, leaderboard would be meaningless.

**Comment by matt-goldman** [comment]
> Alternatively it can be level-based instead of time-based, that we set up different levels for app users from newbies to masters, and users will level up to the next leaderboard when they gain enough points. Ideally this solves two issues,
> 
> * In the early stage of the product when there's not many users, the time-based leaderboard may not look good
> * As users grow, new users may feel uncompetitive seeing how far away they are from the top ones (as Penny mentioned)

I love this - this is a great idea!

**Comment by zl24622** [comment]
It seems we want to get more engagement through competitation. But the product itself is not a game which I like to compete with others. For this product, I would more focus on myself, such as how many points I get, what points I could potentially get, how far to win a reward etc

**Comment by ozairashfaqueSSW** [comment]
It will definitely encourage the new users

**Comment by tkapa** [comment]
Closing and marking as done. 

You can now sort by "This Week" on the leaderboard table :)
