### ISSUE TITLE
✨ Send messages to presenter and event master

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#497]
Cc: @adamcogan 

Hi 
  
### Pain

It would be cool to send messages to the presenter, e.g. questions for the Q&A.

And... have them appear on the YouTube Q&A for a livestream too

Also, as per @adamcogan:

>But what if I'm an attendee and I want to ask someone to turn the air-conditioning down?
>
>Therefore I'd like this feature to be usable for any question
>from
>an attendee
>to
>the Event Master

### Suggested Solution

Add Presenter and Event Master messaging to the app

### Tasks

- [ ] Add event master messaging
- [ ] Add Q&A
- [ ] Integrate with YouTube for livestreams

### Acceptance Criteria

- [ ] Meets Definition of Done
- [ ] User can send questions for Q&A
- [ ] User can send request to Event Master

Thanks!

**Comment by cvionnet** [comment]
Nice feature! We can also imagining enhancing the user engagement and interactivity 
during user groups  by incorporating features like answering micro polls during the presentation, downloading slides...
