### ISSUE TITLE
✨ Install Google Analytics 4

### ISSUE THREAD

**Issue by camillars** [SSWConsulting/SSW.Rewards.Mobile#500]
Cc: @matt-goldman 

Hi 
  
### Pain

Right now we don't have any data/insights on how users interact with the app.

### Suggested Solution

Install Google Analytics 4 - https://support.google.com/analytics/answer/9304153?hl=en and https://support.google.com/analytics/answer/9353532?hl=en

### Tasks

- [ ] Follow https://support.google.com/analytics/answer/9304153?hl=en#:~:text=Create%20a%20new%20Google%20Analytics%204%20property
- [ ] Then https://support.google.com/analytics/answer/9304153?hl=en#stream
- [ ] Finally https://support.google.com/analytics/answer/9289234?sjid=11221117844504175265-SA#linkga

### Acceptance Criteria

- [ ] Meets Definition of Done - get it tested by the Marketing team

### Screenshots

Thanks!

**Comment by AntPolkanov** [comment]
Similar to #489

**Comment by camillars** [comment]
Hi @AntPolkanov 

is there an expectation of when this will be done?

cheers.

**Comment by AntPolkanov** [comment]
@camillars , as per our conversation you would like to have it done before the /NEW conference (15th of May).
I will increase Severity from 3 to 2 and we will discuss with the team what we can do.
