### ISSUE TITLE
🐛 Mobile - Bug Report from DDD |  Camera Scanning Issue on Android

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#543]
Cc: @adamcogan, @Anton-Polkanov, @tkapa, @zacharykeeping, @SSWConsulting/sswadmin 

(Content from email: RE: 🐛 Bug Report from DDD |  Camera Scanning Issue on Android)
Hi @matt-goldman 

### Describe the Bug

As per our Teams on Sat, there seems to be a weird bug with some Androids where it doesn’t recognise a QR code in the app. They could scan the one to download the app just fine, but then when they went to scan one within the app, it wouldn’t work.
 
This happen it Dylan Oliver, Bryden’s son, as well as one other participant. From what I could see, the permissions in the phone were correct.

### Tasks
- [x] Investigate
- [x] Fix
- [x] Reply done to the email 

### Acceptance Criteria

- [x] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [x] Tested on an Android device

### Environment
 - Device: Samsung something (quote Bryden)
 - OS: Android

Thanks!

**Comment by AntPolkanov** [comment]
This bug happens on Android and iOS in the following conditions:
- when the popup with a scan result appears the user either double taps or long taps on the OK button AND
- the camera is still pointing on a QR code triggering another scan while the popup is closing
