### ISSUE TITLE
🐛 Mobile - Bug Report from DDD | Auth issue with Apple ID

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#544]
Cc: @adamcogan @tkapa @Anton-Polkanov @zacharykeeping @SSWConsulting/sswadmin 

(Copy of email RE: 🐛 Bug Report from DDD | Auth issue with Apple ID)
Hi @matt-goldman 

As per our Teams on Sat, there is a weird auth bug when people try to sign into Rewards via their Apple ID. It gets stuck in a loop that only stops if you uninstall the app and start again.
 
This happened to at least 2 people that I spoke to.

### Tasks
- [ ] Investigate
- [ ] Fix
- [ ] Follow up with Apple users to see if they can sign in with Apple ID (Penny, Tylah, Zach etc)
- [ ] Reply done to the email

### Acceptance Criteria

- [ ] Meets Definition of Done

### Environment
 - Device: iPhone 15 Pro Plus
 - OS: iOS

### Screenshots

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/17246482/b65a3789-8381-4711-abfd-ea24e714fde6)
Figure: Log in error from Apple auth

#1 - Identity times out and gets stuck on a blank screen:
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/17246482/8a8decb1-5b57-471c-9990-38212d8e70d4)

Figure: Attempt #1 at signing in through Apple ID – blank screen
 
#2 – Looks like it works but then it’s stuck spinning on the Rewards sign in page:
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/17246482/ca010ea6-7358-43b9-8974-1a4566918a44)

Figure: Attempt #2 at signing in through Apple ID – stuck on sign-in screen

Thanks!

**Comment by tkapa** [comment]
Zac + Tylah have tested this on the mobile app + SugarLearning, and not had any issues. 

This may no longer be an issue.

**Comment by matt-goldman** [comment]
Closed by #577
