### ISSUE TITLE
✨ Admin - DDD Retro | New members page

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#545]
Cc: @adamcogan, @william-liebenberg, @SSWConsulting/sswadmin 

Hi @SSWConsulting/ssw-rewards
  
### Pain

Currently, we have to manually extract new user information from the database after events (DDD, NDC).

### Suggested Solution

It would be awesome to have a way to view new users on the Admin portal.

Ideally this view would allow filtering for new users from a Start Date.

### Tasks

- [ ] Update with API endpoint if required
- [ ] Create Admin Page
- [ ] Get it tested by Penny

### Acceptance Criteria

- [ ] Meets Definition of Done 

Thanks!

**Comment by AntPolkanov** [comment]
Hey @tkapa, we now have the "New Users" page in the Admin portal.
Can this one be closed?

**Comment by tkapa** [comment]
Hey @AntPolkanov,

I think that after /NEW we should follow up with Penny on this one :)
