### ISSUE TITLE
✨ Mobile - DDD Retro | Combine Achievement and Download QR Codes

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#546]
Cc: @adamcogan @william-liebenberg @SSWConsulting/sswadmin 

(From email - DDD Brisbane 2023 Retrospective)
Hi @SSWConsulting/ssw-rewards 
  
### Pain

When running events, we currently need to have 2 QR Codes! One for users to download the app, and another to grant users achievements. 

### Suggested Solution

It would be awesome if we could have one QR code at a booth that people could simply scan twice to download the App and get an achievement.

Some negatives I can think of:
- ❌ Some users could get confused about having to scan the same code twice.
- ❌ We may have to regenerate a download + achievement code for every event we run. However, this could be addressed in the way QR Codes are generated (All codes could now download the App if it isn't installed)

### Tasks

- [ ] Investigate the possibility of combining App download and achievement QR Codes
- [ ] Implement 
- [ ] Test for a new achievement for:
    - [ ] iOS + Android: App not installed
    - [ ] iOS + Android: App already installed 
- [ ] Get it checked by Penny

### Acceptance Criteria

- [ ] Meets Definition of Done

Thanks!
