### ISSUE TITLE
💚 Consolidate .bicep templates and deploy.yml

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#553]
Cc: @SSWConsulting/ssw-rewards 

Hi @matt-goldman 
  
### Pain

We currently have a lot of `.bicep` and GitHub Actions in this project which could be simplified to be more effective.

### Suggested Solution

Consolidate the `.bicep` as much as possible.

### Tasks

- [ ] Consolidate the `.bicep` as much as possible.
- [ ] Consolidate the `admin-az-deploy.yml` and `api-deploy.yml` as much as possible.

### Acceptance Criteria

- [ ] Meets Definition of Done

Thanks!
