### ISSUE TITLE
💚 DevOps - Create .NET MAUI CI/CD Pipeline

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#554]
Cc: @SSWConsulting/ssw-rewards-maintainers 

Hi @matt-goldman 
  
### Pain

We currently don't have tests on PR set up for the .NET MAUI project. 

### Tasks

- [ ] Create `maui-test.yml` to build and test the .NET MAUI project as minimally as possible
- [ ] Create `maui-build.yml` to build all required App artifacts
- [ ] (Optional) Create `maui-deploy.yml` to deploy all artifacts to the Google Play and iOS App Store.

### Acceptance Criteria

- [ ] Meets Definition of Done

Thanks!
