### ISSUE TITLE
💄 Only display "This week" on leaderboard if there is activity this week

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#556]
Cc: @jeanthirion @tkapa @JackDevAU @tomek-i @ricksu978 @kahamason 

Hi 
  
### Pain

As per #491 we now have "This week" filtering on the leaderboard and it is the default. On that issue, a few people commented that this could look bad when there is little or no traffic/volume/engagement.

### Suggested Solution

There was one solution proposed on that thread to introduce levels. I think this bears investigation, as does a thorough analysis of what the best UX for this is that strikes the right balance between not looking like a wasteland while simultaneously not intimidating new users.

In the meantime, I propose this interim method. Which is to hide the "This week" tab if there are no points accrued by any users this week.

### Tasks

- [ ] Add logic to determine whether this week includes any points
- [ ] Hide this week tab if there are no points

### Acceptance Criteria

- [ ] Meets Definition of Done 

Thanks!
