### ISSUE TITLE
💄 UI : Network V3

### ISSUE THREAD

**Issue by 2fernandez** [SSWConsulting/SSW.Rewards.Mobile#561]
CC: @matt-goldman @adamcogan 

(Checked by @matt-goldman)
**Hi Matt,**

- [x] Can you Implement NetworkV3?

## MVP

```[tasklist]
### Networking v3 Page MVP Task List
- [x] 💄 Mobile | Networking User Card Display
- [x] 💄 Mobile | Friends filter (SSW Only)
- [x] 💄 Mobile | To Meet filter (SSW Only)
- [x] 💄 Mobile | SSW filter
```

Thanks 🙂.

Click[ here](https://www.figma.com/proto/YUUbjq13bQB8ZgU6c2SYqd/SSW-Rewards-V2-JFernandez?page-id=1%3A3&type=design&node-id=8-615&viewport=1429%2C370%2C0.5&t=aUDrvMBjzYdpx2uT-1&scaling=scale-down&starting-point-node-id=431%3A12671&mode=design) for Figma Prototype.

![Screenshot 2023-12-29 at 4 49 20 pm](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/27670973/45ebaa2f-04a0-4c2c-bc8c-a3223ad8a356)
**Figure: SSW.Rewards Network Mockup**

**Comment by tkapa** [comment]
As per my conversation with @2fernandez, this page looks more complex than it is. The takeaways are as such:

- "Friends" are simply any person that the user has scanned. This status is **not** necessarily mutual, and doesn't require any "Friend Request" functionality.
- The Green Dots on the cards denote "Friends" of the user, and these are consistent across the filters.
- As MVP, we can implement this page using only SSW People for now.
- Joe now understands that only SSW Users are granted a QR Code for scanning at this time. I will create a new PBI to implement scanning for all users.

I've updated this PBI with the MVP features.

- [ ] ✨ Mobile | All users can be scanned
- [ ] 💄 Mobile/API | Add "Others" filter to the Networking page

**Comment by matt-goldman** [comment]
I recall a conversation around changing these to say something like “SSW | Met | To meet” or something like that. Did we document that somewhere?

**Comment by tkapa** [comment]
Hey @matt-goldman,

> I recall a conversation around changing these to say something like “SSW | Met | To meet” or something like that. Did we document that somewhere?

I'm not sure that I was in that exact conversation that you're referencing. However, I've had essentially the same conversation with @2fernandez. As MVP, we will essentially have this same set up with "Friends" (AKA Met) | "To Meet" | and "SSW"

**Comment by tkapa** [comment]
MVP is now complete - I'm going to close this PBI

**Comment by tkapa** [comment]
(Copied from Email SSW.Rewards | Network v3 Page Done Video)
(Checked by Camilla)
Hey Adam and Seth,
 
I recently implemented Joe’s design for the Network v3 page https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/561
 
This feature is currently released to Beta, and I’ve created a quick and dirty Done video https://youtu.be/2J_glwL5_C8
 
To summarise the key points
The “SSW People” page will be replaced with the “Network” page.
The “Network” page provides the same functionality as the “SSW People” page with the updated look and feel of the V3 UI.
In the future, this page will support all users on the App, and all users will be able to scan each other, driving community engagement.
 
Let me know if you have any feedback or questions 😊
 
Hey Seth,
 
As per my conversation with Camilla, with these changes we can reduce the load for onboarding.
 
❌ Staff Bio - In the “Network” page, a Staff member’s Bio won’t be displayed.
❌ Full-body picture – We no longer need a full-body picture for everyone to be added to their profile.
We can now just give them their SSW People headshot to use OR just let them use their own profile picture
❌ Skills – Users now only have up to 3 skills
 
Review the onboarding process for SSW Rewards
Update the SugarLearning Items relating to SSW.Rewards Onboarding
 
<This is as per the rule https://ssw.com.au/rules/escalate-key-updates/>
