### ISSUE TITLE
♻️ Warnings as weeoes

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#565]
Cc: @tkapa @zacharykeeping 

Hi 

### Pain

While merging in the code with git history from the Admin Portal and API (see #564) we had over 900 warnings. To not be blocked by this, we disabled treat warnings as errors.

### What code could be improved?

Treat warnings as errors should be re-enabled, and all the warnings should be resolved.

### Tasks

- [ ] Re-enable treat warnings as errors
- [ ] Resolve all the warnings

### Acceptance Criteria

- [ ] Meets Definition of Done 

Thanks!
