### ISSUE TITLE
✨ Mobile - User settings

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#582]
Cc: @matt-goldman @tkapa 

Hi team
  
### Pain

The new V3 flyout design contains a Settings button that we currently have no use for so is hidden.

### Suggested Solution

We should consider the types of settings we should allow the user to modify and implement a settings page where this can be managed.

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/198825b9-bf89-487b-a2c5-5e7fb0ca888e)

**Figure: Mockup by Ken**

### Tasks

- [ ] Investigate options
- [ ] Implement settings page
- [ ] Add a new Settings page
- [ ] Move the Delete Profile functionality into the Settings page
- [ ] Update the Delete Profile button in the Flyout to open the Settings page

Thanks!

**Comment by zacharykeeping** [comment]
Done - a Settings page has been implemented.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/fc5c1850-8f22-45cb-8cef-d4076f6699a4" width="400" />

**Figure: Simplified flyout with new Settings option**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/e76bc4a7-c2be-4b1d-b83e-1918683d1e46" width="400" />

**Figure: New Settings page**
