### ISSUE TITLE
✨ UI - Implement SSW.QuizGPT for Rewards 

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#597]
Cc: @SSWConsulting/ssw-rewards-maintainers 

Hi @tkapa, @lukecookssw 
  
### Pain

We recently proof of concepted SSW.QuizGPT, and it's been much easier than we thought to do.

### Tasks

- [ ] Implement the new Quiz page from the Figma #559 
- [ ] Use SSW.QuizGPT for answering questions
- [ ] API requests should not block the user from finishing the quiz
- [ ] If the user finished the quiz before all responses are back, play an animation and wait until requests are finished
- [ ] Store the Quiz response objects locally until the user is finished with the Quiz
- [ ] Confirm whether or not the user got the answers correct, assign achievement or show results

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

### Screenshots

Thanks!

**Comment by adamcogan** [comment]
Hey Tylah
I know you have done the Azure approval now with a v4 that I have approved.

For completeness I think you should add a first step
      “Get the Azure $ annual costs approved as per https://www.ssw.com.au/rules/azure-budgets/ “

The other important step is to get the mockups approved as per the Michael Jackson rule

-a
www.ssw.com.au<http://www.ssw.com.au>



[cid:ssw-circle(1)_4c7259a6-23f6-49e5-b933-230ca304562e.png]

Adam Cogan
SSW Chief Architect + Microsoft Regional Director
Stalk: SSW People<https://www.ssw.com.au/people/Adam-Cogan?utm_source=emailsignature>   |   Walk: SSW Sydney<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Talk: +61 4 1985 1995<https://www.ssw.com.au/ssw/Company/ContactUs.aspx>
[cid:youtube-icon_b8b5cda9-a973-4973-8763-cf3d4922e060.png] <https://www.youtube.com/c/SSWTV>    [cid:linkedin-icon_b153ac9a-eb66-47d9-9c51-ad20b42b8a0a.png]  <https://www.linkedin.com/company/ssw/>    [cid:twitter-icon_16ddd2de-0a0c-4b56-9986-6c5968e517d2.png]  <https://twitter.com/SSW_TV>    [cid:teams-icon_552803c2-9c44-4267-b563-7fe1a7a0e589.png] ***@***.***>


        ⭐️ 2023 Microsoft Partner of the Year Finalist<https://www.ssw.com.au/SSW/Consulting/Case-Study/Shepherd-Centre.aspx>

From: Tylah Kapa [SSW] ***@***.***>
Sent: Friday, January 19, 2024 11:57 AM
To: SSWConsulting/SSW.Rewards.Mobile ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SSWConsulting/SSW.Rewards.Mobile] ✨ UI - Implement SSW.QuizGPT for Rewards (Issue #597)


Cc: @SSWConsulting/ssw-rewards-maintainers<https://github.com/orgs/SSWConsulting/teams/ssw-rewards-maintainers>

Hi @tkapa<https://github.com/tkapa>, @lukecookssw<https://github.com/lukecookssw>

Pain

We recently proof of concepted SSW.QuizGPT, and it's been much easier than we thought to do.

Tasks

 *   [ ] Implement the new Quiz page from the Figma #559<https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/559>
 *   [ ] Use SSW.QuizGPT for answering questions
 *   [ ] API requests should not block the user from finishing the quiz
 *   [ ] If the user finished the quiz before all responses are back, play an animation and wait until requests are finished
 *   [ ] Store the Quiz response objects locally until the user is finished with the Quiz
 *   [ ] Confirm whether or not the user got the answers correct, assign achievement or show results

Acceptance Criteria

 *   [ ] Meets Definition of Done - {{ LINK }}
 *   [ ] ...

More Information
Screenshots

Thanks!

**Comment by adamcogan** [comment]
Done – I agree and have updated the Issue.



[cid:ssw-circle(1)_4c7259a6-23f6-49e5-b933-230ca304562e.png]

Tylah Kapa
SSW Software Engineer
Stalk: SSW People<https://www.ssw.com.au/people/Tylah-Kapa?utm_source=emailsignature>   |   Walk: SSW Brisbane<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Talk: +61 451 380 844<https://www.ssw.com.au/ssw/Company/ContactUs.aspx>
[cid:youtube-icon_b8b5cda9-a973-4973-8763-cf3d4922e060.png] <https://www.youtube.com/c/SSWTV>    [cid:linkedin-icon_b153ac9a-eb66-47d9-9c51-ad20b42b8a0a.png]  <https://www.linkedin.com/company/ssw/>    [cid:twitter-icon_16ddd2de-0a0c-4b56-9986-6c5968e517d2.png]  <https://twitter.com/SSW_TV>    [cid:teams-icon_552803c2-9c44-4267-b563-7fe1a7a0e589.png] ***@***.***>


        ⭐️ 2023 Microsoft Partner of the Year Finalist<https://www.ssw.com.au/SSW/Consulting/Case-Study/Shepherd-Centre.aspx>

From: Adam Cogan [SSW] ***@***.***>
Date: Monday, 29 January 2024 at 17:59
To: SSWConsulting/SSW.Rewards.Mobile ***@***.***>, SSWConsulting/SSW.Rewards.Mobile ***@***.***>, Tylah Kapa [SSW] ***@***.***>
Cc: Subscribed ***@***.***>, Mehmet Ozdemir [SSW] ***@***.***>, William Liebenberg [SSW] ***@***.***>, Luke Cook [SSW] ***@***.***>, Chris Schultz [SSW] ***@***.***>, Matt Goldman [SSW] ***@***.***>
Subject: RE: [SSWConsulting/SSW.Rewards.Mobile] ✨ UI - Implement SSW.QuizGPT for Rewards (Issue #597)
Hey Tylah
I know you have done the Azure approval now with a v4 that I have approved.

For completeness I think you should add a first step
      “Get the Azure $ annual costs approved as per https://www.ssw.com.au/rules/azure-budgets/ “

The other important step is to get the mockups approved as per the Michael Jackson rule
-a
www.ssw.com.au<http://www.ssw.com.au/>
















Adam Cogan   |   SSW Chief Architect + Microsoft Regional Director<http://www.ssw.com.au/People/Adam-Cogan?utm_source=emailsignature>   |    +61 4 1985 1995<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>


From: Tylah Kapa [SSW] ***@***.***>
Sent: Friday, January 19, 2024 11:57 AM
To: SSWConsulting/SSW.Rewards.Mobile ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [SSWConsulting/SSW.Rewards.Mobile] ✨ UI - Implement SSW.QuizGPT for Rewards (Issue #597)


Cc: @SSWConsulting/ssw-rewards-maintainers<https://github.com/orgs/SSWConsulting/teams/ssw-rewards-maintainers>

Hi @tkapa<https://github.com/tkapa>, @lukecookssw<https://github.com/lukecookssw>

Pain

We recently proof of concepted SSW.QuizGPT, and it's been much easier than we thought to do.

Tasks

 *   [ ] Implement the new Quiz page from the Figma #559<https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/559>
 *   [ ] Use SSW.QuizGPT for answering questions
 *   [ ] API requests should not block the user from finishing the quiz
 *   [ ] If the user finished the quiz before all responses are back, play an animation and wait until requests are finished
 *   [ ] Store the Quiz response objects locally until the user is finished with the Quiz
 *   [ ] Confirm whether or not the user got the answers correct, assign achievement or show results

Acceptance Criteria

 *   [ ] Meets Definition of Done - {{ LINK }}
 *   [ ] ...

More Information
Screenshots

Thanks!
