### ISSUE TITLE
🐛 Mobile | Stabilisation before release

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#609]
### Pain
Work on UI v3 introduced new issues in different parts of the app.

### What code could be improved?
Find as much issues as you can and fix.

### Tasks

- [x] Android: the app crashes when the user taps on achievements on the Home page (@AntPolkanov)
- [x] The app crashes when you navigate to a user's profile page from the Leaderboard (@AntPolkanov)

- [x] Leaderboard page - top 3 leaders are overlayed by the list on small screens
<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/486829b0-5897-4b11-87f1-057af4fa7edd" width=200 style="margin-bottom:20"/>

---

- [x] The leaders control displays stale data when you switch between This Week | This Month | This Year | All Time. (@AntPolkanov)
<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/4acd7adf-7c37-4c38-9400-85fe093bed6c" width=200 />

---

- [x] Quizzes UI is not responsive (@AntPolkanov)

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/bddb3d68-f4a3-45c5-bb8b-64d203bbed50" width=200/>

---

- [x] Android: the app icon doesn't comply with Android standards, hence, cropped

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/d765f232-43a9-43bf-904a-41a12bd3512e)

---

- [x] Login Failure on the very first app start after the update.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/d835ec64-65c5-448e-b8a7-abe087022728" width=200/>
