### ISSUE TITLE
💄 Sprint 18 stretch goals

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#615]
UI polish items:

```[tasklist]
### Tasks
- [x] Add a lottie animation when the quiz is being evaluated
- [x] OS keyboard and editor (enable multiline)
- [x] Updating quizzes with correct images and thumbnails
- [ ] https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/718
- [x] Add chevrons to quiz answers
- [ ] https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/716
```

**Comment by tkapa** [comment]
> * Updating quizzes with correct images and thumbnails

Done - I asked Betty for these assets and she pulled through, legend.

**Comment by tkapa** [comment]
> Add a lottie animation when the quiz is being evaluated

Done - Sophie now greet the user with a cute quote while loading responses

**Comment by tkapa** [comment]
I am moving this issue #716 out of this PBI, as it requires more work.
