### ISSUE TITLE
🐛 Mobile - Mobile UI issues

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#621]
Hi team

### Describe the Bug

As per @AntPolkanov's other PBI at #609, he found a number of issues with the mobile app:

- [x] QR code scanner scans codes, but always shows "Something went wrong here" animation
- [x] QR code is displayed for users who are not SSW employees
- [x] QR code scanner doesn't pick up SSW employees QR codes
- [x] Sometimes a user can submit a quiz answer twice, and when retrying the final quiz completion check it can resubmit the last answer
- [x] Switching pages after loading the Earn page can result in the autoscrolling behaving sporadically
- [x] Titles only show up on the Earn pages
- [x] Remove v2 home page and replace with Leaderboard
- [x] Login can be stuck on a spinner (only seen on iOS)
- [x] Camera icon is not showing on profile page (#654)

### Tasks
- [x] Investigate
- [x] Fix
