### ISSUE TITLE
✨ Admin | Improve the Data displayed and manipulated in the Admin Portal

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#671]
Cc: @adamcogan @matt-goldman @zacharykeeping 

Hi @tkapa 

### Describe the Bug

Over the course of NDC, the Rewards team had to manually Query the Database multiple times in order to fix certain things. I would consider this a failure of the Admin Portal to provide the functionality that we need and have full control over the application.

These include: 
- Reverting a Reward Claim (Accidental Scan)
- Resetting the Leaderboard for NDC Sydney
- Gathering information (How many people have LinkedIn URLs set in the app?)

### Tasks
- [ ] Create new issues from the following tasks 
- [ ] ✨ Admin | Reverting/Deleting a Reward claim for a user
- [ ] ✨ Mobile | Require User Confirmation when Claiming a Reward (might be addressed by UI v3)
- [ ] ✨ Admin | Add Leaderboard Reset / "Conference Mode"
- [ ] ✨ Admin | Easy way to view User Profiles

Thanks!

**Comment by matt-goldman** [comment]
> Resetting the Leaderboard for NDC Sydney

This is a symptom of testing in production. Let's give this some thought and I think probably deprioritise it compared to the others.
