### ISSUE TITLE
💄 Mobile | v3 Settings Page

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#685]
Cc: @adamcogan @wicksipedia @matt-goldman @zacharykeeping 

Hi @tkapa 
  
### Pain

We currently have the `Delete Profile` button on the Flyout for the application.

This risks the user accidentally requesting Profile deletion.

### Suggested Solution

As per the Figma, there's currently a `Settings` page that we don't have made, which should likely house this functionality.

However, we don't have a design for the Settings page.

### Tasks

- [ ] Add a new `Settings` page
- [ ] Move the `Delete Profile` functionality into the `Settings` page
- [ ] Update the `Delete Profile` button in the Flyout to open the `Settings` page

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

Thanks!

**Comment by AntPolkanov** [comment]
Duplicate ot #582.
Closing this one.
