### ISSUE TITLE
✨ QuizGPT: Set "return" key to something better like "go" or "submit"

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#688]
Cc: @UlyssesMaclaren

Hi 
  
### Pain

Given that we have an `Entry` now rather than `Editor` and therefore no multi-line answers, can we configure the keyboard so the `Return` key says something more meaningful.

### Suggested Solution

Change `Return` to `Go` on the keyboard for QuizGPT questions

### Tasks

- [ ] Implement on iOS
- [ ] Implement on Android

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

### Screenshots

Thanks!

**Comment by AntPolkanov** [comment]
PR #710 adds a multiline Editor.
This issue is not relevant anymore (cc: @tkapa)
