### ISSUE TITLE
♻️ Replace `ICommand` with `[RelayCommand]`

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#711]
### Pain

Wiring up command bindings in .NET MAUI is cumbersome, and we're not doing it consistently throughout the app.

### What code could be improved?

Get rid of all the `ICommand` instances. Instead, use the `[RelayCommand]` source generator in the MVVM Community Toolkit.

### Tasks

- [x] Get rid of the `ICommand` instances
- [x] Decorate the relevant methods with the `[RelayCommand]` attribute
- [x] Ensure the naming of methods follows the convention, so that the bindings will still work

### Acceptance Criteria

- [x] Meets Definition of Done

Thanks!
