### ISSUE TITLE
💄 Mobile | Update quiz results page (requires designer review)

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#716]
Pain:

The existing Quiz Results page leaves a lot to be desired. While we had some great designs from Joe we had to quickly adapt and change the existing design to fit with the AI Quiz structure.

Solution:

- [x] Solicit a new design for the Results page
- [x] Update this PBI with an @adamcogan approved design screenshot
- [x] Implement the design

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/844
- [x] Implement Design
```

**Comment by zacharykeeping** [comment]
Done - this was completed here https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/844
