### ISSUE TITLE
💄 Mobile | Add "AI driven quizzes" badge

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#718]
Pain:

Our current mobile UI does a bad job of conveying to users that our Quizzes are powered by AI, arguably one of the coolest features of the app at the moment :)

Solution:

- [x] Solicit a design to add a "Powered by AI" badge to the `earn` page
- [ ] Update this PBI with an @adamcogan approved Design
- [ ] Implement the design

```[tasklist]
### Tasks
- [ ] https://github.com/SSWConsulting/SSW.Rewards.Mobile/issues/845
```
