### ISSUE TITLE
💄 UI | OnboardingPage 2024

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#729]
cc: @adamcogan 

Hi Anton

I see Mi Band 6
FYI today it is called  Xiaomi Mi Band 7 Smart Wristband

1. Change Mi Band 6
   To
   Mi Band

2. Change
    “earn a Mi Wrist Band”
    To
    “earn a Mi Band Smart Wristband”
 
3. Change ‘except more’
    To
     ‘with extra ’

4. Can you move everything up a bit so the last line has no problems on any of the 6 pages

5. I think the product name should appear somewhere.
    Change from
     Welcome!!﻿
To
     Welcome to SSW Rewards

### Tasks

- [ ] Change wordings
- [ ] Make the page responsive

### Screenshots

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/c6996c76-9cfd-41c5-822f-47869b2c2136)

Thanks!

**Comment by AntPolkanov** [comment]
The pages needs to be re-designed as some of the prizes are not relevant anymore and we are moving towards V3 (cc: @2fernandez)

**Comment by 2fernandez** [comment]
**Hi @adamcogan ,** 

- [ ] 1. Can you approve the SSW.Rewards Onboarding design as seen in this video: https://youtu.be/7BJ7IXnhT1w

---

**Hi @AntPolkanov**, 
As per our conversation, I've brought the SSW Rewards onboarding in line with the new SSW.Rewards design.

The figma prototype can be seen [here](https://www.figma.com/proto/YUUbjq13bQB8ZgU6c2SYqd/SSW-Rewards-V2-JFernandez?page-id=1%3A3&type=design&node-id=431-12671&viewport=-1429%2C-3305%2C1&t=hdCYXzDtWc4oYjqX-1&scaling=scale-down&starting-point-node-id=431%3A12671&mode=design).

Once @adamcogan has approved the design.

- [ ] 1. Can you implement the new design?


Thanks 🙂

**Comment by tkapa** [comment]
Blocked - @AntPolkanov can this be closed with #787

**Comment by AntPolkanov** [comment]
@tkapa , yep closing this one.
