### ISSUE TITLE
✨ Mobile | Reward redemption

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#736]
Cc: @tkapa @matt-goldman @AntPolkanov @kristenhu

Hi team
  
As per our conversation with Camilla, the following should be done to handle reward redemptions in the app:

### Tasks

- [ ] In the admin portal, allow for rewards to be enabled and disabled
- [ ] In the mobile app, capture the user's address on redemption
    - [ ] only allow addresses from Australia
- [ ] Send an email to marketing with this information to be processed

Thanks!
