### ISSUE TITLE
💄 Mobile/API | Add "Others" filter to the Networking page

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#740]
Cc: @matt-goldman @zacharykeeping @Anton-Polkanov 

Hi @tkapa 
  
### Pain

Blocked by: #739 

The user currently doesn't have a way to see any community members that they have scanned or are yet to meet.

### Suggested Solution

Add the "Others" Filter to the Networking page, and display External Scanned users to the "Friends" filter.

### Tasks

- [ ] Investigate
- [ ] Add API Endpoints if Required
- [ ] Implement UI

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] User can see any non-SSW people that they have and have not scanned in the Networking page

### Screenshots

Thanks!

**Comment by matt-goldman-ssw** [comment]
Note that #739 is completed so this is not blocked by that now.

@bettybondoc I seem to recall we had a chat about this - did we agree on an approach here? This is regarding showing everyone in the app (not just SSW peeps).

**Comment by bettybondoc** [comment]
@matt-goldman-ssw 

I think we agreed to have 3 tabs:
- Following (people we have scanned)
- Followers (people who scanned us)
- To Meet (people whom we haven't scanned yet and haven't been scanned by us)

And then use the green QR code icon to show that we have scanned them

**Comment by matt-goldman** [comment]
Thanks @bettybondoc. I wasn't sure what we were doing with non-SSW folks. I can see that now under "to meet" we have only SSWers, but for the other 2 you can see SSWers plus externals that have scanned you or you have scanned. That's what we agreed right? Otherwise the "to meet" tab will have too many people.

**Comment by bettybondoc** [comment]
@matt-goldman-ssw 

Yes - only showing SSWers under "To Meet"

I think we also discussed additional features that could enhance the UX if we decide to show everyone. Otherwise, it may result in an endless scroll of users with accounts.

Here are some potential features to improve the UX and make "To Meet" more intuitive:
- **Check-in:** Display only those currently checked in at the conference under "To Meet". This way users won't have to look for missing people.
- **Search:** Add a search function within each tab ("Following," "Followers," and "To Meet") to help manage longer lists. This search should be placed strategically to avoid users mistaking it for a global search.
- **Hide Inactive Accounts:** Reduce clutter by hiding accounts that haven't been active for a specific period (e.g., 2 months)
