### ISSUE TITLE
♻️ Simplify the codebase by using a source generator for bindable properties

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#744]
Hi 

### Pain

We have a lot of custom controls with bindable properties. It's a bugbear of .NET MAUI (and previously Xamarin) support that you have to hand-roll these in a way that could be simplified or better handled by the framework.

### What code could be improved?

We could use this library to simplify all these: https://github.com/rrmanzano/maui-bindableproperty-generator

### Tasks

- [ ] Import library
- [ ] Update bindable properties to be auto-generated
- [ ] Update docs to indicate that we use this lib

### Acceptance Criteria

- [ ] Meets Definition of Done 

Thanks!
