### ISSUE TITLE
🐛 Mobile | Prevent double taps

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#750]
Double taps case all sorts of trouble like a page opening twice or even app crash

### Expected Behavior
Only single taps can be performed

### Tasks 
- [x] Fix Leaderboard list items
- [x] Fix Quiz list items
- [x] Fix Scanner Ok button
- [x] Fix Edit profile picture

Thanks!
