### ISSUE TITLE
♻️ Mobile | Update GetNetworkProfileListHandler to use AutoMapper

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#759]
(Checked by @matt-goldman)
Cc: @matt-goldman @Anton-Polkanov 

Hi @tkapa 

### Pain

As per my conversation with Matt G, we're implementing the new Network feature. But this doesn't correspond to an existing entity. A working approach has been added in #757, but this may not be the best approach.

### What code could be improved?

Unknown at this stage - Review to ensure this is the best way

### Tasks

- [ ] Review current approach to Network feature
- [ ] Refactor if necessary

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

### Screenshots

Thanks!
