### ISSUE TITLE
✨ API | Infrastructure for Azure Maps

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#762]
Cc: @tkapa 

Hi 
  
### Pain

#745 adds address search functionality that relies on Azure Maps. This is currently using a key from my own Azure tenant.

### Suggested Solution

Set up the IaC to deploy Azure Maps to the resource groups

### Tasks

- [x] Deploy the Azure Maps resource
- [x] Add the key to Key Vault
- [x] Update dev secrets in Keeper to use the dev instance key

### Acceptance Criteria

- [x] Meets Definition of Done

### Screenshots

Thanks!

**Comment by tkapa** [comment]
As per my conversation with the Rewards Team, this is now done.
