### ISSUE TITLE
♻️ Warnings in code

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#763]
Cc: @tkapa 

Hi 

### Pain

There are currently several warnings throughout the codebase. This is unprofessional and pollutes debug logs and PRs. It also prevents us enabling "warnings as error" in the config.

### What code could be improved?

Remove the current warnings

### Tasks

- [ ] Agree the right approach for resolving these (e.g. full indiscriminate refactor, suppressions in code, suppressions in file, etc.)
- [ ] Implement changes
- [ ] Re-enable warnings as errors

### Acceptance Criteria

- [ ] Meets Definition of Done
- [ ] No warnings in code
- [ ] Warnings as errors re-enabled

### Screenshots

Thanks!
