### ISSUE TITLE
♻️ Review how we are handling time across the whole stack

### ISSUE THREAD

**Issue by matt-goldman** [SSWConsulting/SSW.Rewards.Mobile#782]
Cc: @tkapa @Anton-Polkanov @sethdaily 

Hi

### Pain

We are not handling time consistently across the app. Some values are UTC, some are not, and some are not working at all.

### What code could be improved?

We should use UTC everywhere, or DateTimeOffSet.

### Tasks

- [ ] Research appropriate options
- [ ] Write an ADR
- [ ] Implement changes

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] Times are conssitent - eg., scan an achievement, awarded at shows a time that makes sense
