### ISSUE TITLE
✨ Mobile | LinkedIn integration

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#799]
Hi team

### Pain

As per Adam's email (Rewards Leaderboard on Day 1 of NDC - lets try to add a little more LinkedIn ❤️) from NDC, we want to better integrate LinkedIn on profiles within the app.

As the previous LinkedIn profile functionality was non-functional and no longer exists in the V3 UI, this will first depend on the completion of IdentityServer's integration of LinkedIn (https://github.com/SSWConsulting/SSW.IdentityServer/issues/83).

Ideally, the new integration is done via IdentityServer / OAuth to LinkedIn. However, we can add a similar feature into the 2024 UI Settings Page.

### Tasks

- [x] #685 

```[tasklist]
### Tasks
- [x] 💄 Mobile | Add "LinkedIn" to Settings Page
- [x] User gets an Achievement for adding the LinkedIn Details
- [ ] 💄 Mobile | Display LinkedIn badge on the Profile page for users that have linked accounts #875 
- [ ] Done Video | Show functionality in action :)
```

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] ...

### More Information

Thanks!

**Comment by AntPolkanov** [comment]
Done video.

https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/5a363e55-234b-44c3-8b2e-20d15be82975
