### ISSUE TITLE
✨ Mobile/Admin | Fix issues with cheating

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#809]
Cc: @AntPolkanov @zacharykeeping @matt-goldman @adamcogan @sethdaily 

To Myself,

We've recently had an issue where users were able to cheat to gain points in the app. Initially, this wasn't a problem with this. However, it's now an issue because there is a $$ incentive to get more points for rewards.

### Describe the Bug
- QR Codes are Base 64 Encoded with easy to replicate base strings. Meaning anyone with access to the names of SSW Employees can generate their own employee QR Code.

### Tasks

- [ ] Investigate
- [ ] Fix
- [ ] Check that QR Codes are updated in the Admin Portal
- [ ] Done Video
- [ ] Tell Camilla/Seth that any printed QR Codes are now zz'ed

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] ...

### Environment

- Device: [e.g. iPhone 12]

### Screenshots

Thanks!
