### ISSUE TITLE
✨ Mobile | Make Flyout page accessible

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#838]
Cc: @adamcogan 

### Pain

The Flyout page becomes messy once the user increases the font size.

### Suggested Solution

1. Truncate labels which display user name and email
2. Vertically align email and the red mail icon

### Tasks

- [ ] Implement suggestions 1 and 2
- [ ] Figure out why the padding between icons and labels (e.g. Log Out) goes away when font increases. Fix it.

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

### Screenshots

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/214bee4d-49bc-4f6b-876e-95442668e69f" width=250 />

**Figure 1**: ❌ Truncated labels and messy UI

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/d433204b-8770-4053-a8d8-5255d1ea5680" width=250 />

**Figure 2:** Font size settings to reproduce the issue

Thanks!

**Comment by AntPolkanov** [comment]
Check with @zacharykeeping and then with @adamcogan once it's fixed.
