### ISSUE TITLE
✨ Mobile | Add tap animation to all tappable UI elements

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#857]
### Pain

Currently when users tap on a button or a list item, there is no any tap animation. If there is slight delay, users might think they didn't tap the button.

### Suggested Solution

To improve UX, add tap animation to all buttons, tappable labels, list items and icons.

### Tasks

- [ ] Find all tappable elements
- [ ] Make it so that animation applies globally

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!
