### ISSUE TITLE
🐛 Admin/API | Some staff achievement types not marked correctly

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#866]
Hi team

### Describe the Bug

There's an issue where some staff achievements (i.e. when a user scans a staff QR code) are marked incorrectly and are set to other things such as "Attended", which is then shown incorrectly in the app (eg. "Zach Keeping checked in to Tylah Kapu" rather than "Zach Keeping scanned Tylah Kapu").

### Tasks

- [x] Investigate why these are set incorrectly
- [x] Fix current achievements
- [x] Ensure future achievements are set correctly

Thanks!

**Comment by zacharykeeping** [comment]
Done - this should be all fixed now.

It seems like it's only happening from some old achievements that were set incorrectly to "Attended" rather than "Scanned", so it's probably a holdover from an old issue. More recent achievements all seem to be set correctly, and it looks like it's being set correctly in the code so this shouldn't happen going forward. I've gone through and fixed up all the old achievements.
