### ISSUE TITLE
✨ Mobile | Make Activity items clickable

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#872]
Hi team

### Pain

On the Activity page, currently if you tap on any item it does nothing. This should be updated so that tapping on an item brings up that person's profile page.

### Tasks

- [ ] Update the Activity page to link to a user's profile when their activity is tapped
- [ ] The podium on the leaderboard page also doesn't handle taps. This should also be updated to link to that person's profile.

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by zacharykeeping** [comment]
Done - this has been implemented.
