### ISSUE TITLE
🐛 Mobile | Quizzes | Incorrect snackbar on the Result page

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#874]
### Describe the Bug

After successfully completing the React quiz, a snackbar appears with incorrect data.

### Tasks

- [x] Fix the icon
- [x] Change wording from "... the React Quiz quiz" to "... the React Quiz"
- [x] Change the color of the component where 3/3 is displayed from red to green

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

### Environment

- Device: [e.g. iPhone 12]

### Screenshots

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/9ed9ef6c-762f-4b0b-b5ea-410ac07ba90b" width=300 />

**Figure:** Snackbar with incorrect data

Thanks!

**Comment by zacharykeeping** [comment]
Done - this no longer shows the incorrect icon.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/33ca66ce-0e8b-4e9d-bc4b-668a8498ee24" width="400" />

**Figure: Updated quiz results page with trophy icon, fixed text, and green background colour on the score**
