### ISSUE TITLE
✨ Mobile | Show LinkedIn against profiles

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#875]
Hi team

Now that we have the ability to add a LinkedIn profile in Settings, we now need to show these against profiles.

### Tasks

- [ ] Show a LinkedIn icon on items on the Leaderboard if that user has a LinkedIn profile set
  - [ ] Maybe show these icons on the Network page as well
- [x] On profile pages, show that user's LinkedIn profile and allow them to tap and open that link

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by AntPolkanov** [comment]
> Show a LinkedIn icon on items on the Leaderboard if that user has a LinkedIn profile set

Not done. 
The purpose of the Leaderboard is to provide visibility and recognition to users, so LinkedIn information doesn't seem to belong there.
We also don't have enough space on the Leaderboard list item to accommodate social media information as we already shorten names and points.

When a user adds their LinkedIn profile, that action will appear on the Activity page.

> Maybe show these icons on the Network page as well

The Network page might be the right place to show such information, but the page will require a re-design to accommodate the varying number of social media platforms.

> On profile pages, show that user's LinkedIn profile and allow them to tap and open that link

Done, see the screenshot below.



<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/a10e1741-90a3-44d5-9f29-79e57789d953" width=300/>

**Figure:** LinkedIn profile icon which will open a browser when tapped.
