### ISSUE TITLE
🐛 Mobile | Fixes required after v3.0.19 release

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#886]
### Tasks

- [x] 1. The app crashes when the user taps on the LinkedIn icon. That happens if the Uri is invalid
- [x] 2. Place social media icons above the Skill Set
- [x] 3. Make the entire Settings and Log Out panels clickable. At that moment you need to tap on the label
- [x] 4. Popup overlay doesn't cover the entire screen on iOS
- [x] 5. Do not reload the Redeem list every time the Redeem popup is closed
- [x] 6. Align the look of About SSW popup with the other popups
- [x] 7. Align corner radius for buttons across the app
- [x] 8. #888 

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!
