### ISSUE TITLE
♻️ Mobile | Improve clarity of Settings page

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#887]
Cc: @adamcogan @AntPolkanov 

Hi team

### Pain

As per my conversation with @adamcogan, the Settings page is a bit confusing and lacks some clarity.

### Tasks

- [ ] Rename "Settings" to "My Settings" in the Flyout
- [ ] Move the "Intro" button into an "About" section

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by zacharykeeping** [comment]
Done - the Settings page has been improved.

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/7a214c19-a233-4e0f-ab5b-1e976b366852" width="400" />

**Figure: Renamed Settings button**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/d11f5f29-c67c-4e1b-88f9-a2dc64b64556" width="400" />

**Figure: Updated Settings page**

<img src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/11418832/9fba3e3e-0ebe-4974-9387-d24f05854342" width="400" />

**Figure: Updated About popup**
