### ISSUE TITLE
✨ Mobile | Capture and display user's company URL

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#892]
Cc: @adamcogan

Hi team

### Pain

As per @adamcogan's email "SSW Rewards - show the company name", we want to be able to allow a user to enter their own Company URL, and have that displayed instead of "Community".

### Tasks

- [x] In Settings, allow a user to enter a Company URL
- [ ] On a user's profile, show the Company URL if it exists
- [ ] Where it shows "Community" on places like the Leaderboard, show the Company URL instead
- [ ] Get checked by Adam

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!
