### ISSUE TITLE
✨ Mobile | Pull-to-refresh on Earn and Redeem pages

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#922]
Hi team

### Pain

We currently have pull-to-refresh on most of our main tabs, however on Earn and Redeem this isn't implemented, so if quizzes or prizes are changed they won't be visible in the app unless the user restarts it.

### Suggested Solution

We should add pull-to-refresh to these other pages.

### Tasks

- [ ] Add pull-to-refresh to the Earn page
- [ ] Add pull-to-refresh to the Redeem page

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!
