### ISSUE TITLE
✨ API | Second onelink.to link for new users

### ISSUE THREAD

**Issue by zacharykeeping** [SSWConsulting/SSW.Rewards.Mobile#988]
Hi team

We currently use one onelink.to link for both Google Form email templates. We should create a second one and implement it so that both emails have unique links, and as such we can get analytics for new users vs existing users.

### Tasks

- [ ] Create second link
- [ ] Implement on both email templates

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md

Thanks!

**Comment by zacharykeeping** [comment]
Done - the email templates now user separate links for new and existing users.
