### ISSUE TITLE
✨ API/Admin | Admins can create a default sort order for Rewards

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#992]
Cc:

Hi

### Pain

For Copenhagen Developers Festival, there was a feature suggested that Rewards might be able to have a default sort order defined by Admins to prioritise certain rewards.

### Suggested Solution

In the admin portal, let admins define a default order that rewards will appear in.

### Tasks

- [ ] Does the Carousel negate the need for this?
- [ ] Implement or close

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] ...

### Screenshots

Thanks!
